export const keyMap = [
    //lower row
    {key: 'z', note: 'C', octave: '0'},
    {key: 'x', note: 'D', octave: '0'},
    {key: 'c', note: 'E', octave: '0'},
    {key: 'v', note: 'F', octave: '0'},
    {key: 'b', note: 'G', octave: '0'},
    {key: 'n', note: 'A', octave: '0'},
    {key: 'm', note: 'B', octave: '0'},
    {key: ',', note: 'C', octave: '1'},
    {key: '.', note: 'D', octave: '1'},
    {key: '/', note: 'E', octave: '1'},
    //middle row
    {key: 's', note: 'C#', octave: '0'},
    {key: 'd', note: 'D#', octave: '0'},
    {key: 'g', note: 'F#', octave: '0'},
    {key: 'h', note: 'G#', octave: '0'},
    {key: 'j', note: 'A#', octave: '0'},
    {key: 'l', note: 'C#', octave: '1'},
    {key: ';', note: 'D#', octave: '1'},
    //upper row
    {key: 'q', note: 'C', octave: '1'},
    {key: 'w', note: 'D', octave: '1'},
    {key: 'e', note: 'E', octave: '1'},
    {key: 'r', note: 'F', octave: '1'},
    {key: 't', note: 'G', octave: '1'},
    {key: 'y', note: 'A', octave: '1'},
    {key: 'u', note: 'B', octave: '1'},
    {key: 'i', note: 'C', octave: '2'},
    {key: 'o', note: 'D', octave: '2'},
    {key: 'p', note: 'E', octave: '2'},
    //number row
    {key: '2', note: 'C#', octave: '1'},
    {key: '3', note: 'D#', octave: '1'},
    {key: '5', note: 'F#', octave: '1'},
    {key: '6', note: 'G#', octave: '1'},
    {key: '7', note: 'A#', octave: '1'},
    {key: '9', note: 'C#', octave: '2'},
    {key: '0', note: 'D#', octave: '2'},
    ]