export const DATA_POOL_LIST_REQUEST = 'DATA_POOL_LIST_REQUEST'
export const DATA_POOL_LIST_SUCCESS = 'DATA_POOL_LIST_SUCCESS'
export const DATA_POOL_LIST_FAIL = 'DATA_POOL_LIST_FAIL'
export const DATA_POOL_LIST_RESET = 'DATA_POOL_LIST_RESET'

export const DATA_POOL_INSERT_REQUEST = 'DATA_POOL_INSERT_REQUEST'
export const DATA_POOL_INSERT_SUCCESS = 'DATA_POOL_INSERT_SUCCESS'
export const DATA_POOL_INSERT_FAIL = 'DATA_POOL_INSERT_FAIL'

export const DATA_POOL_DELETE_REQUEST = 'DATA_POOL_DELETE_REQUEST'
export const DATA_POOL_DELETE_SUCCESS = 'DATA_POOL_DELETE_SUCCESS'
export const DATA_POOL_DELETE_FAIL = 'DATA_POOL_DELETE_FAIL'

export const DATA_POOL_UPDATE_REQUEST = 'DATA_POOL_UPDATE_REQUEST'
export const DATA_POOL_UPDATE_SUCCESS = 'DATA_POOL_UPDATE_SUCCESS'
export const DATA_POOL_UPDATE_FAIL = 'DATA_POOL_UPDATE_FAIL'
export const DATA_POOL_UPDATE_RESET = 'DATA_POOL_UPDATE_RESET'