export const SET_DISPLAY_FOCUS_SUCCESS = 'SET_DISPLAY_FOCUS_SUCCESS'
export const SET_DISPLAY_FOCUS_FAIL = 'SET_DISPLAY_FOCUS_FAIL'
export const SET_DISPLAY_FOCUS_INITIALIZE = 'SET_DISPLAY_FOCUS_INITIALIZE'