export const SET_GLOBAL_POSITION_SUCCESS = 'SET_GLOBAL_POSITION_SUCCESS'
export const SET_GLOBAL_POSITION_FAIL = 'SET_GLOBAL_POSITION_FAIL'
export const SET_GLOBAL_POSITION_INITIALIZE = 'SET_GLOBAL_POSITION_INITIALIZE'