
export const INSTRUMENT_NAME_SET_SUCCESS = 'INSTRUMENT_NAME_LIST_SUCCESS'
export const INSTRUMENT_NAME_SET_FAIL = 'INSTRUMENT_NAME_LIST_FAIL'
export const INSTRUMENT_NAME_INITIALIZE= 'INSTRUMENT_NAME_INITIALIZE'