export const MAP_CHORDS_TO_PLAYER_SUCCESS = 'MAP_CHORDS_TO_PLAYER_SUCCESS'
export const MAP_CHORDS_TO_PLAYER_FAIL = 'MAP_CHORDS_TO_PLAYER_FAIL'
export const MAP_CHORDS_TO_PLAYER_INITIALIZE = 'MAP_CHORDS_TO_PLAYER_INITIALIZE'