export const SET_PLAY_HIGHLIGHT_SUCCESS = 'SET_PLAY_HIGHLIGHT_SUCCESS'
export const SET_PLAY_HIGHLIGHT_FAILURE = 'SET_PLAY_HIGHLIGHT_FAILURE'
export const SET_PLAY_HIGHLIGHT_INITIALIZE = 'SET_PLAY_HIGHLIGHT_INITIALIZE'