export const POOL_LIST_REQUEST = 'POOL_LIST_REQUEST'
export const POOL_LIST_SUCCESS = 'POOL_LIST_SUCCESS'
export const POOL_LIST_FAIL = 'POOL_LIST_FAIL'
export const POOL_LIST_RESET = 'POOL_LIST_RESET'

export const POOL_INSERT_REQUEST = 'POOL_INSERT_REQUEST'
export const POOL_INSERT_SUCCESS = 'POOL_INSERT_SUCCESS'
export const POOL_INSERT_FAIL = 'POOL_INSERT_FAIL'

export const POOL_DELETE_REQUEST = 'POOL_DELETE_REQUEST'
export const POOL_DELETE_SUCCESS = 'POOL_DELETE_SUCCESS'
export const POOL_DELETE_FAIL = 'POOL_DELETE_FAIL'

export const POOL_UPDATE_REQUEST = 'POOL_UPDATE_REQUEST'
export const POOL_UPDATE_SUCCESS = 'POOL_UPDATE_SUCCESS'
export const POOL_UPDATE_FAIL = 'POOL_UPDATE_FAIL'
export const POOL_UPDATE_RESET = 'POOL_UPDATE_RESET'